steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/gcp-devops-project/gcpdevops:latest", "."]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/gcp-devops-project/gcpdevops:latest"]

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - --filename=gke.yaml
      - --image=gcr.io/gcp-devops-project/gcpdevops:latest
      - --location=us-central1-a
      - --cluster=gcp-devops-project

options:
  logging: CLOUD_LOGGING_ONLY
