substitutions:
  _CLUSTER_NAME: gcp-devops-project
  _CLUSTER_LOCATION: us-central1-a
  _CLUSTER_PROJECT: gcp-devops-project

steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops:$SHORT_SHA", "."]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/gcpdevops:$SHORT_SHA"]

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - --filename=gke.yaml
      - --image=gcr.io/$PROJECT_ID/gcpdevops:$SHORT_SHA
      - --location=$_CLUSTER_LOCATION
      - --cluster=$_CLUSTER_NAME
      - --project=$_CLUSTER_PROJECT

options:
  logging: CLOUD_LOGGING_ONLY
