steps:
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]

- name: gcr.io/cloud-builders/docker
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]

- name: gcr.io/cloud-builders/gke-deploy
  args:
  - run
  - --filename=k8s.yaml         # <— we'll point to a single file with all resources
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-central1-a    # make sure this matches your cluster’s zone/region
  - --cluster=gke-gcp-devops

options:
  logging: CLOUD_LOGGING_ONLY

